export const POSTGRES_SCHEMA = `
CREATE TABLE IF NOT EXISTS "VaiTro" (
  "VaiTroID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaVaiTro" varchar(40) NOT NULL UNIQUE,
  "TenVaiTro" varchar(160) NOT NULL,
  "CapDo" integer NOT NULL DEFAULT 0,
  "MoTa" text
);
CREATE TABLE IF NOT EXISTS "Quyen" (
  "QuyenID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaQuyen" varchar(60) NOT NULL UNIQUE,
  "TenQuyen" varchar(160) NOT NULL,
  "MoTa" text
);
CREATE TABLE IF NOT EXISTS "PhanQuyenVaiTro" (
  "PhanQuyenVaiTroID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "VaiTroID" integer NOT NULL REFERENCES "VaiTro" ("VaiTroID") ON DELETE CASCADE,
  "QuyenID" integer NOT NULL REFERENCES "Quyen" ("QuyenID") ON DELETE CASCADE,
  UNIQUE ("VaiTroID", "QuyenID")
);
CREATE TABLE IF NOT EXISTS "NguoiDung" (
  "NguoiDungID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "TenDangNhap" varchar(100) NOT NULL UNIQUE,
  "MatKhauHash" text NOT NULL,
  "HoTen" varchar(200) NOT NULL,
  "Email" varchar(254) NOT NULL UNIQUE,
  "SoDienThoai" varchar(40) NOT NULL DEFAULT '',
  "VaiTroID" integer REFERENCES "VaiTro" ("VaiTroID"),
  "TrangThai" varchar(40) NOT NULL DEFAULT 'HOAT_DONG',
  "NgayTao" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "NgayCapNhat" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "PhanQuyenNguoiDung" (
  "PhanQuyenNguoiDungID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NguoiDungID" integer NOT NULL REFERENCES "NguoiDung" ("NguoiDungID") ON DELETE CASCADE,
  "QuyenID" integer NOT NULL REFERENCES "Quyen" ("QuyenID") ON DELETE CASCADE,
  "CapQuyenBoi" integer REFERENCES "NguoiDung" ("NguoiDungID") ON DELETE SET NULL,
  UNIQUE ("NguoiDungID", "QuyenID")
);
CREATE TABLE IF NOT EXISTS "DiemNoiBat" (
  "DiemNoiBatID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaDiem" varchar(100) NOT NULL UNIQUE,
  "TenDiem" varchar(200) NOT NULL,
  "LoaiDiem" varchar(40) NOT NULL,
  "MoTa" text NOT NULL DEFAULT '',
  "X" double precision NOT NULL DEFAULT 0,
  "Y" double precision NOT NULL DEFAULT 0,
  "Latitude" numeric(10,7),
  "Longitude" numeric(10,7),
  "NgayTao" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "ToaNha" (
  "ToaNhaID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaToaNha" varchar(40) NOT NULL UNIQUE,
  "TenToaNha" varchar(200) NOT NULL,
  "MoTa" text NOT NULL DEFAULT '',
  "X" double precision NOT NULL DEFAULT 0,
  "Y" double precision NOT NULL DEFAULT 0,
  "ChieuRong" double precision NOT NULL DEFAULT 200,
  "ChieuCao" double precision NOT NULL DEFAULT 140,
  "SoTang" integer NOT NULL DEFAULT 1,
  "MauSac" varchar(30) NOT NULL DEFAULT '#2563eb',
  "XiengVaoX" double precision NOT NULL DEFAULT 0,
  "XiengVaoY" double precision NOT NULL DEFAULT 0,
  "Latitude" numeric(10,7),
  "Longitude" numeric(10,7),
  "NgayTao" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "PhongHoc" (
  "PhongHocID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ToaNhaID" integer REFERENCES "ToaNha" ("ToaNhaID") ON DELETE SET NULL,
  "SoPhong" varchar(100) NOT NULL UNIQUE,
  "TenPhong" varchar(200) NOT NULL,
  "Tang" integer NOT NULL DEFAULT 1,
  "MaQR" varchar(200) NOT NULL UNIQUE,
  "TrangThai" varchar(40) NOT NULL DEFAULT 'ACTIVE',
  "MoTa" text NOT NULL DEFAULT '',
  "LoaiPhong" varchar(40) NOT NULL DEFAULT 'CLASSROOM',
  "X" double precision NOT NULL DEFAULT 0,
  "Y" double precision NOT NULL DEFAULT 0,
  "ChieuRong" double precision NOT NULL DEFAULT 180,
  "ChieuCao" double precision NOT NULL DEFAULT 120,
  "CuaX" double precision NOT NULL DEFAULT 0,
  "CuaY" double precision NOT NULL DEFAULT 0,
  "Latitude" numeric(10,7),
  "Longitude" numeric(10,7),
  "NgayTao" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "LoaiThietBi" (
  "LoaiThietBiID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "MaLoai" varchar(60) NOT NULL UNIQUE,
  "TenLoai" varchar(160) NOT NULL,
  "MoTa" text NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS "ThietBi" (
  "ThietBiID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "PhongHocID" integer REFERENCES "PhongHoc" ("PhongHocID") ON DELETE SET NULL,
  "LoaiThietBiID" integer REFERENCES "LoaiThietBi" ("LoaiThietBiID") ON DELETE SET NULL,
  "MaThietBi" varchar(100) NOT NULL UNIQUE,
  "TenThietBi" varchar(200) NOT NULL,
  "Model" varchar(160) NOT NULL DEFAULT '',
  "SerialNumber" varchar(160) NOT NULL DEFAULT '',
  "ViTri" varchar(200) NOT NULL DEFAULT '',
  "TrangThai" varchar(40) NOT NULL DEFAULT 'ACTIVE',
  "MaQR" varchar(200) NOT NULL UNIQUE,
  "MoTa" text NOT NULL DEFAULT '',
  "NgayTao" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "BaoHong" (
  "BaoHongID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "NguoiBaoID" integer REFERENCES "NguoiDung" ("NguoiDungID") ON DELETE SET NULL,
  "PhongHocID" integer REFERENCES "PhongHoc" ("PhongHocID") ON DELETE SET NULL,
  "ThietBiID" integer REFERENCES "ThietBi" ("ThietBiID") ON DELETE SET NULL,
  "KyThuatVienNhanID" integer REFERENCES "NguoiDung" ("NguoiDungID") ON DELETE SET NULL,
  "TieuDe" varchar(200) NOT NULL,
  "MoTa" text NOT NULL DEFAULT '',
  "AnhURL" text,
  "MucDo" varchar(30) NOT NULL DEFAULT 'MEDIUM',
  "TrangThai" varchar(40) NOT NULL DEFAULT 'PENDING',
  "NgayTao" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "NgayCapNhat" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "HuongDanSuDung" (
  "HuongDanID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ThietBiID" integer REFERENCES "ThietBi" ("ThietBiID") ON DELETE CASCADE,
  "TieuDe" varchar(200) NOT NULL,
  "NoiDung" text NOT NULL DEFAULT '',
  "NgayTao" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS "LogBaoTri" (
  "LogBaoTriID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "BaoHongID" integer REFERENCES "BaoHong" ("BaoHongID") ON DELETE SET NULL,
  "KyThuatVienID" integer REFERENCES "NguoiDung" ("NguoiDungID") ON DELETE SET NULL,
  "HanhDong" text NOT NULL,
  "NgayTao" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);
`;
